sudo: required
language: node_js
node_js:
  - "8"
  - "10"

cache:
  directories:
    - $HOME/.yarn-cache

install:
  - npm install -g @angular/cli
  - yarn install --frozen-lockfile

script:
  - npm run lint
  - ng test ng-wormhole --watch=false --code-coverage --browsers ChromeHeadless

addons:
  chrome: stable
